### ISSUE TITLE
generate trapezoids instead of triangle mesh

### ISSUE THREAD

**Issue by sidorares** [mattdesl/extrude-polyline#5]
I'd like to use this module to make path strokes server side with X11/XRender, but unfortunately AddTriangles Xrender seem to be unable to stitch edges of triangles without visible border. To draw solid shapes with xrender it is recommended to split it into array of horizontal trapezoids.

Can you suggest an easy way to modify `Stroke.build()` generate trapezoids instead of triangle mesh?

**Comment by sidorares** [comment]
https://github.com/sidorares/ntk/issues/9

**Comment by mattdesl** [comment]
Hmm, it does not seem too easy. This module assumes triangles only. 

Good luck! :smile:

**Comment by sidorares** [comment]
Actually I was wrong about xrender: 

>   When mask-format is not None, triangles are rendered in the
>     following way with the effective mask computed in mask-format:
> 
> ```
>   tmp = temporary alpha picture (in mask-format)
>     Combine (Zero, tmp, tmp, None)
>     for each triangle
>         Combine (Add, tmp, triangle, None)
>     Combine (op, dst, source, tmp)
> ```
> 
>   When mask-format is None, triangles are rendered in the order
>     specified directly to the destination:
> 
> ```
>   for each triangle
>         Combine (op, dst, source, triangle)
> ```

So I added mask and now ( using your triangulation ) I have this 

![screen shot 2016-01-07 at 9 41 48 am](https://cloud.githubusercontent.com/assets/173025/12157058/14c0a408-b523-11e5-95ba-7f6396820bec.png)

Instead of this

![screen shot 2016-01-07 at 9 42 46 am](https://cloud.githubusercontent.com/assets/173025/12157055/12a38c3a-b523-11e5-9ff0-3f242e6dfbd6.png)
